services:
  - type: web
    name: tempgo-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --threads 4 --bind 0.0.0.0:$PORT run:app
    healthCheckPath: /api/health
